# Generated by Django 2.2.4 on 2019-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecms',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homecms',
            name='header_text_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homecms',
            name='header_text_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
