# Generated by Django 2.2.4 on 2019-12-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0003_categoriescms'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriescms',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
