# Generated by Django 2.2.4 on 2019-12-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0004_categoriescms_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesCMS',
            new_name='CategoryCMS',
        ),
    ]
