# Generated by Django 2.2.7 on 2019-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0006_auto_20191227_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('phone1', models.BigIntegerField()),
                ('phone2', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
