# Generated by Django 2.2.7 on 2019-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0007_contactcms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcms',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
