# Generated by Django 2.2.7 on 2019-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0008_contactcms_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_info', models.TextField()),
                ('about_image', models.ImageField(upload_to='about_images')),
            ],
        ),
    ]
