# Generated by Django 2.2.4 on 2019-12-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0011_auto_20191227_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_us', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
