# Generated by Django 2.2.4 on 2019-12-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0012_footercms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('form', models.TextField()),
            ],
        ),
    ]
