# Generated by Django 2.2.4 on 2019-12-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0013_contactusform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='form',
            field=models.TextField(blank=True, null=True),
        ),
    ]
