# Generated by Django 2.2.7 on 2020-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0014_auto_20191231_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCMSDraggable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
    ]
