# Generated by Django 2.2.7 on 2020-02-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0015_homecmsdraggable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableHomeComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeCMSDraggable',
            new_name='ActiveHomeComponents',
        ),
    ]
