# Generated by Django 2.2.7 on 2020-02-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0016_auto_20200211_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activehomecomponents',
            name='value',
        ),
        migrations.RemoveField(
            model_name='availablehomecomponents',
            name='value',
        ),
    ]
