# Generated by Django 2.2.7 on 2020-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0017_auto_20200211_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveHomeComponents',
        ),
        migrations.DeleteModel(
            name='AvailableHomeComponents',
        ),
    ]
