# Generated by Django 2.2.4 on 2019-12-22 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('added_date', models.DateField(default=datetime.datetime.now)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_added_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=datetime.datetime.now)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('stage', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_app_link', models.CharField(max_length=200)),
                ('active_users', models.IntegerField()),
                ('product_video', models.FileField(blank=True, null=True, upload_to='product_videos/')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('login_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('house_no', models.IntegerField(blank=True, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('display_pic', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('login_status', models.BooleanField(default=False)),
                ('last_login_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_updates', models.TextField()),
                ('update_video', models.FileField(blank=True, null=True, upload_to='product_update_videos')),
                ('added_date', models.DateField(default=datetime.datetime.now)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_added_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=datetime.datetime.now)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('key_team_members', models.CharField(blank=True, max_length=200, null=True)),
                ('incubators', models.CharField(blank=True, max_length=500, null=True)),
                ('accelerators', models.CharField(blank=True, max_length=500, null=True)),
                ('investors', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_launch', models.DateField()),
                ('name_of_founders', models.CharField(blank=True, max_length=500, null=True)),
                ('year_founded', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(default='State', max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('partnerships_associations', models.CharField(blank=True, max_length=500, null=True)),
                ('funding_round', models.IntegerField(blank=True, default=0, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_added_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='startup_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.StartUp'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
