# Generated by Django 2.2.4 on 2020-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='startup_images'),
        ),
    ]
