# Generated by Django 2.2.4 on 2019-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='update_video',
            field=models.FileField(blank=True, null=True, upload_to='product_update_videos/'),
        ),
    ]
