# Generated by Django 2.2.4 on 2019-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_auto_20191223_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
    ]
