# Generated by Django 2.2.4 on 2020-01-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_startup_thumbnail'),
        ('baseApp', '0004_updates_deleted_flag'),
    ]

    operations = [
    ]
