# Generated by Django 2.2.7 on 2020-01-27 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseApp', '0005_merge_20200121_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='startup_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_products', to='baseApp.StartUp'),
        ),
        migrations.CreateModel(
            name='ProductRatingsAndReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=0)),
                ('reviews', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
