# Generated by Django 2.2.7 on 2020-01-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_auto_20200127_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productratingsandreviews',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
