# Generated by Django 2.2.7 on 2020-02-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_productratingsandreviews_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch_Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_upload', models.FileField(blank=True, null=True, upload_to='ppt_upload/')),
                ('pitch_video_upload', models.FileField(blank=True, null=True, upload_to='pitch_video_upload/')),
                ('offer_upload', models.FileField(blank=True, null=True, upload_to='offer_upload/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.StartUp')),
            ],
        ),
    ]
