# Generated by Django 2.2.7 on 2020-02-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_pitch_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitch_campaign',
            old_name='pitch_video_upload',
            new_name='image_or_video_upload',
        ),
        migrations.RemoveField(
            model_name='pitch_campaign',
            name='offer_upload',
        ),
    ]
